[package]
name = "gtm-sync"
version = "0.1.0"
authors = ["tavo <tavo.annus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.6"
git2 = "0.13"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.7"